// Official Seed Data for Tesacola Empire Nigeria
// Note: As specified in Section 83 & 123, all demo items are clearly marked [DEMO / SEED DATA]

export const SEED_CATEGORIES = [
  {
    id: "cat-men",
    name: "Men's Footwear",
    slug: "men",
    description: "Handcrafted Nigerian leather footwear built for precision, durability, and boardroom confidence.",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "cat-women",
    name: "Women's Footwear",
    slug: "women",
    description: "Refined, comfortable, and architecturally shaped leather shoes crafted for leadership and occasion.",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "cat-bags",
    name: "Bags & Portfolios",
    slug: "bags",
    description: "Full-grain executive bags, laptop cases, clutches, and travel leather crafted for longevity.",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "cat-belts",
    name: "Belts",
    slug: "belts",
    description: "Solid brass hardware with hand-burnished edge finishing in premium bridle and calfskin leather.",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "cat-leather-goods",
    name: "Small Leather Goods",
    slug: "leather-goods",
    description: "Minimalist card sleeves, bifold wallets, passport folios, and key holders.",
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "cat-leather-wear",
    name: "Leather Wear",
    slug: "leather-wear",
    description: "Bespoke jackets, vests, and precision-cut leather wear crafted with bespoke tailoring.",
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "cat-children",
    name: "Children's Footwear",
    slug: "children",
    description: "Durable school shoes and formal leather footwear engineered for resilient daily wear.",
    sortOrder: 7,
    isActive: true,
  },
];

export const SEED_COLLECTIONS = [
  {
    id: "col-executive",
    name: "The Executive Collection",
    slug: "executive",
    description: "Commanding corporate footwear and leather business essentials crafted for African industry leaders.",
    heroImage: "/seed/executive.jpg",
    isPublished: true,
    sortOrder: 1,
  },
  {
    id: "col-heritage",
    name: "The Heritage Collection",
    slug: "heritage",
    description: "Traditional hand-stitched welted construction celebrating indigenous Nigerian craftsmanship.",
    heroImage: "/seed/heritage.jpg",
    isPublished: true,
    sortOrder: 2,
  },
  {
    id: "col-travel",
    name: "The Travel Collection",
    slug: "travel",
    description: "Heavy-duty weekender bags and versatile slip-on drivers for international journeys.",
    heroImage: "/seed/travel.jpg",
    isPublished: true,
    sortOrder: 3,
  },
  {
    id: "col-occasion",
    name: "The Occasion Collection",
    slug: "occasion",
    description: "Patent finishes, wholecut oxfords, and embroidered velvet-leather hybrids for celebratory moments.",
    heroImage: "/seed/occasion.jpg",
    isPublished: true,
    sortOrder: 4,
  },
];

export const SEED_PRODUCTS = [
  {
    id: "prod-1",
    name: "[DEMO / SEED DATA] Tesacola Sovereign Wholecut Oxford",
    slug: "sovereign-wholecut-oxford",
    sku: "TSA-MN-OXF-001",
    shortDescription: "Cut from a single flawless piece of premium full-grain calf leather with hand-burnished deep obsidian finish.",
    fullDescription: "The Sovereign Wholecut Oxford represents the absolute pinnacle of Tesacola shoemaking. Cut from a single continuous piece of selected Nigerian vegetable-tanned calfskin, it eliminates unnecessary seams, creating an unbroken sculptural silhouette. Built on our proprietary ergonomic last, each pair undergoes 18 hours of precision shaping, hand-buffing, and edge-dressing.",
    productStory: "Conceived as an uncompromising boardroom statement piece. Every contour follows the natural anatomy of the foot, delivering commanding presence without sacrificing all-day ease.",
    material: "Full-Grain Nigerian Calfskin Upper, Vegetable-Tanned Leather Sole & Lining",
    colour: "Obsidian Black with subtle burnished toe",
    construction: "Blake-Stitched Leather Sole with Brass Protective Taps",
    price: 185000,
    currency: "NGN",
    status: "IN_STOCK",
    productionTime: "Ready to ship (48 hours dispatch)",
    deliveryInfo: "2–4 working days nationwide Nigeria; 5–8 days DHL Express International.",
    careInstructions: "Condition with beeswax cream monthly. Use cedar shoe trees between wears.",
    isFeatured: true,
    isPublished: true,
    categoryId: "cat-men",
    images: [
      {
        id: "img-1-1",
        productId: "prod-1",
        url: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=1000&q=80",
        altText: "Tesacola Sovereign Wholecut Oxford front profile",
        isMain: true,
        sortOrder: 1,
      },
      {
        id: "img-1-2",
        productId: "prod-1",
        url: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=1000&q=80",
        altText: "Hand-burnished leather sole detail",
        isMain: false,
        sortOrder: 2,
      },
    ],
    variants: [
      { id: "var-1-41", productId: "prod-1", name: "Size 41", sku: "TSA-MN-OXF-001-41", size: "EU 41 / UK 7", colour: "Obsidian Black", priceAdjustment: 0, stockQuantity: 6, isAvailable: true },
      { id: "var-1-42", productId: "prod-1", name: "Size 42", sku: "TSA-MN-OXF-001-42", size: "EU 42 / UK 8", colour: "Obsidian Black", priceAdjustment: 0, stockQuantity: 12, isAvailable: true },
      { id: "var-1-43", productId: "prod-1", name: "Size 43", sku: "TSA-MN-OXF-001-43", size: "EU 43 / UK 9", colour: "Obsidian Black", priceAdjustment: 0, stockQuantity: 8, isAvailable: true },
      { id: "var-1-44", productId: "prod-1", name: "Size 44", sku: "TSA-MN-OXF-001-44", size: "EU 44 / UK 10", colour: "Obsidian Black", priceAdjustment: 0, stockQuantity: 5, isAvailable: true },
      { id: "var-1-45", productId: "prod-1", name: "Size 45", sku: "TSA-MN-OXF-001-45", size: "EU 45 / UK 11", colour: "Obsidian Black", priceAdjustment: 0, stockQuantity: 3, isAvailable: true },
    ],
  },
  {
    id: "prod-2",
    name: "[DEMO / SEED DATA] Tesacola Artisan Belgian Loafer",
    slug: "artisan-belgian-loafer",
    sku: "TSA-MN-LOA-002",
    shortDescription: "Supple reverse suede and glove calfskin with hand-piped apron and champagne gold accent detail.",
    fullDescription: "A modern homage to classic European lounging luxury, re-engineered for the West African climate. Unlined glove calfskin provides glove-like softness from day one, paired with an all-leather flex-sole and Tesacola's hand-turned binding.",
    productStory: "Designed for effortless elegance from corporate afternoons to weekend soirees.",
    material: "Hand-Selected Glove Calfskin & Velvety Suede",
    colour: "Midnight Obsidian & Antique Tan",
    construction: "Hand-Turned Belgian Apron with Flexible Leather Outsole",
    price: 145000,
    currency: "NGN",
    status: "IN_STOCK",
    productionTime: "Ready to ship (48 hours dispatch)",
    deliveryInfo: "2–4 working days nationwide Nigeria; 5–8 days DHL Express International.",
    careInstructions: "Brush suede lightly with brass-bristle brush. Treat smooth leather with neutral balm.",
    isFeatured: true,
    isPublished: true,
    categoryId: "cat-men",
    images: [
      {
        id: "img-2-1",
        productId: "prod-2",
        url: "https://images.unsplash.com/photo-1582845512747-e42001c95638?auto=format&fit=crop&w=1000&q=80",
        altText: "Tesacola Artisan Belgian Loafer",
        isMain: true,
        sortOrder: 1,
      },
    ],
    variants: [
      { id: "var-2-41", productId: "prod-2", name: "Size 41", sku: "TSA-MN-LOA-002-41", size: "EU 41 / UK 7", colour: "Midnight", priceAdjustment: 0, stockQuantity: 8, isAvailable: true },
      { id: "var-2-42", productId: "prod-2", name: "Size 42", sku: "TSA-MN-LOA-002-42", size: "EU 42 / UK 8", colour: "Midnight", priceAdjustment: 0, stockQuantity: 10, isAvailable: true },
      { id: "var-2-43", productId: "prod-2", name: "Size 43", sku: "TSA-MN-LOA-002-43", size: "EU 43 / UK 9", colour: "Midnight", priceAdjustment: 0, stockQuantity: 7, isAvailable: true },
      { id: "var-2-44", productId: "prod-2", name: "Size 44", sku: "TSA-MN-LOA-002-44", size: "EU 44 / UK 10", colour: "Midnight", priceAdjustment: 0, stockQuantity: 4, isAvailable: true },
    ],
  },
  {
    id: "prod-3",
    name: "[DEMO / SEED DATA] Tesacola Executive Briefcase Portfolio",
    slug: "executive-briefcase-portfolio",
    sku: "TSA-BG-BRF-001",
    shortDescription: "Architectural structured briefcase crafted from heavy bridle leather with solid brass champagne hardware.",
    fullDescription: "Constructed to protect your most sensitive documents and 16-inch laptops. Features dual reinforced gusseted compartments, pen loops, padded interior suede lining, and a detachable padded leather shoulder strap.",
    productStory: "Built to mature with character over decades of commercial negotiations.",
    material: "Full-Grain Vegetable Tanned Bridle Leather, Solid Brass Cast Hardware",
    colour: "Obsidian Black with Gold Hardware",
    construction: "Saddle-Stitched Edge Seams with Hand-Beveled Beeswax Burnishing",
    price: 240000,
    currency: "NGN",
    status: "MADE_TO_ORDER",
    productionTime: "7–10 working days hand-crafting time",
    deliveryInfo: "Shipped immediately upon completion via insured courier.",
    careInstructions: "Polish with rich leather balm twice a year. Keep dry.",
    isFeatured: true,
    isPublished: true,
    categoryId: "cat-bags",
    images: [
      {
        id: "img-3-1",
        productId: "prod-3",
        url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1000&q=80",
        altText: "Tesacola Executive Briefcase Portfolio",
        isMain: true,
        sortOrder: 1,
      },
    ],
    variants: [
      { id: "var-3-one", productId: "prod-3", name: "Standard 16-inch", sku: "TSA-BG-BRF-001-STD", size: "40cm x 30cm x 9cm", colour: "Obsidian Black", priceAdjustment: 0, stockQuantity: 4, isAvailable: true },
    ],
  },
  {
    id: "prod-4",
    name: "[DEMO / SEED DATA] Tesacola Duchess Sculpted Mule",
    slug: "duchess-sculpted-mule",
    sku: "TSA-WM-MUL-001",
    shortDescription: "Architectural pointed-toe slip-on mule featuring a stacked leather kitten heel and champagne gold lining.",
    fullDescription: "The Duchess Mule redefines modern executive womenswear. Hand-molded across an elongated feminine last, it blends graceful proportions with ergonomic arch support and an ultra-soft lambskin insole.",
    productStory: "A masterclass in restraint and quiet luxury for women navigating high-stakes environments.",
    material: "Glazed Calfskin Upper, Nappa Lambskin Insole, Stacked Leather Heel",
    colour: "Ivory Cream & Obsidian Trim",
    construction: "Cemented Construction with Hand-Carved Stacked Leather Heel",
    price: 135000,
    currency: "NGN",
    status: "IN_STOCK",
    productionTime: "Ready to ship (48 hours dispatch)",
    deliveryInfo: "2–4 working days nationwide Nigeria; 5–8 days international.",
    careInstructions: "Wipe with damp microfibre cloth. Store in cotton dust bag.",
    isFeatured: true,
    isPublished: true,
    categoryId: "cat-women",
    images: [
      {
        id: "img-4-1",
        productId: "prod-4",
        url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1000&q=80",
        altText: "Tesacola Duchess Sculpted Mule",
        isMain: true,
        sortOrder: 1,
      },
    ],
    variants: [
      { id: "var-4-37", productId: "prod-4", name: "Size 37", sku: "TSA-WM-MUL-001-37", size: "EU 37 / UK 4", colour: "Ivory Cream", priceAdjustment: 0, stockQuantity: 5, isAvailable: true },
      { id: "var-4-38", productId: "prod-4", name: "Size 38", sku: "TSA-WM-MUL-001-38", size: "EU 38 / UK 5", colour: "Ivory Cream", priceAdjustment: 0, stockQuantity: 8, isAvailable: true },
      { id: "var-4-39", productId: "prod-4", name: "Size 39", sku: "TSA-WM-MUL-001-39", size: "EU 39 / UK 6", colour: "Ivory Cream", priceAdjustment: 0, stockQuantity: 6, isAvailable: true },
      { id: "var-4-40", productId: "prod-4", name: "Size 40", sku: "TSA-WM-MUL-001-40", size: "EU 40 / UK 7", colour: "Ivory Cream", priceAdjustment: 0, stockQuantity: 3, isAvailable: true },
    ],
  },
  {
    id: "prod-5",
    name: "[DEMO / SEED DATA] Tesacola Signature Monogram Bridle Belt",
    slug: "signature-monogram-bridle-belt",
    sku: "TSA-BL-SIG-001",
    shortDescription: "35mm English bridle leather belt with solid brass custom curved buckle and hand-stitched keeper.",
    fullDescription: "Forged from 4mm dense saddle-grade steerhide that will not stretch or warp. Hand-edged with 7 layers of heated wax coating and finished with our bespoke champagne gold buckle.",
    productStory: "The foundational accessory of the Tesacola wardrobe.",
    material: "Full-Grain English Bridle Leather, Solid Cast Brass Buckle",
    colour: "Rich Chocolate Brown with Antique Gold Hardware",
    construction: "Single Piece Solid Hide with Hand-Stitched Keeper",
    price: 45000,
    currency: "NGN",
    status: "IN_STOCK",
    productionTime: "Ready to ship (48 hours dispatch)",
    deliveryInfo: "2–4 working days nationwide Nigeria.",
    careInstructions: "Wipe with soft cloth. Buff with natural saddle soap when needed.",
    isFeatured: false,
    isPublished: true,
    categoryId: "cat-belts",
    images: [
      {
        id: "img-5-1",
        productId: "prod-5",
        url: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=1000&q=80",
        altText: "Tesacola Signature Bridle Belt",
        isMain: true,
        sortOrder: 1,
      },
    ],
    variants: [
      { id: "var-5-32", productId: "prod-5", name: "Waist 32-34", sku: "TSA-BL-SIG-001-32", size: "32–34 inches", colour: "Chocolate Brown", priceAdjustment: 0, stockQuantity: 15, isAvailable: true },
      { id: "var-5-36", productId: "prod-5", name: "Waist 36-38", sku: "TSA-BL-SIG-001-36", size: "36–38 inches", colour: "Chocolate Brown", priceAdjustment: 0, stockQuantity: 20, isAvailable: true },
      { id: "var-5-40", productId: "prod-5", name: "Waist 40-42", sku: "TSA-BL-SIG-001-40", size: "40–42 inches", colour: "Chocolate Brown", priceAdjustment: 0, stockQuantity: 10, isAvailable: true },
    ],
  },
  {
    id: "prod-6",
    name: "[DEMO / SEED DATA] Tesacola Imperial Card Folio",
    slug: "imperial-card-folio",
    sku: "TSA-LG-CRD-001",
    shortDescription: "Ultra-slim six-pocket calfskin card holder with central cash compartment and blind-debossed crest.",
    fullDescription: "Constructed with paper-thin skived calf leather pockets lined with Japanese silk. Slides unnoticed into tailored trouser or jacket pockets while holding 8 cards and folded banknotes securely.",
    productStory: "Minimalism engineered with uncompromising structural rigidity.",
    material: "French Box Calf Leather, Silk Moire Lining",
    colour: "Obsidian Black",
    construction: "Hand-Creased Edges with Heat-Sealed Edge Paint",
    price: 32000,
    currency: "NGN",
    status: "IN_STOCK",
    productionTime: "Ready to ship (48 hours dispatch)",
    deliveryInfo: "2–4 working days nationwide Nigeria.",
    careInstructions: "Keep away from excessive moisture.",
    isFeatured: false,
    isPublished: true,
    categoryId: "cat-leather-goods",
    images: [
      {
        id: "img-6-1",
        productId: "prod-6",
        url: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=1000&q=80",
        altText: "Tesacola Imperial Card Folio",
        isMain: true,
        sortOrder: 1,
      },
    ],
    variants: [
      { id: "var-6-one", productId: "prod-6", name: "Standard", sku: "TSA-LG-CRD-001-STD", size: "10cm x 7.5cm", colour: "Obsidian Black", priceAdjustment: 0, stockQuantity: 25, isAvailable: true },
    ],
  },
];

export const SEED_FAQS = [
  {
    id: "faq-1",
    question: "Where are Tesacola products manufactured?",
    answer: "All Tesacola footwear, bags, and leather goods are precision crafted in our dedicated Nigerian manufacturing facilities, utilizing both traditional hand-welting techniques and modern industrial finishing machinery.",
    category: "MANUFACTURING",
    sortOrder: 1,
    isPublished: true,
  },
  {
    id: "faq-2",
    question: "What is the difference between Production Time and Transit Time?",
    answer: "Production Time refers to the workshop craft schedule (e.g. 7–10 working days for Made-to-Order bespoke articles, or 48 hours dispatch for In-Stock items). Transit Time is the duration taken by our logistics partners (DHL/GIG) once your package leaves our dispatch hub.",
    category: "SHIPPING",
    sortOrder: 2,
    isPublished: true,
  },
  {
    id: "faq-3",
    question: "How do I care for my Tesacola leather footwear?",
    answer: "Clean off surface dust with a horsehair brush after each wear. Apply a high-grade beeswax conditioning cream monthly to nourish the pores, and always insert cedar shoe trees to absorb moisture and preserve structural form.",
    category: "CARE",
    sortOrder: 3,
    isPublished: true,
  },
  {
    id: "faq-4",
    question: "Do you offer private-label manufacturing for corporate or diaspora brands?",
    answer: "Yes. Our commercial B2B division partners with retailers, corporate entities, and international labels for contract manufacturing and bespoke private-label runs. Enquiries can be submitted directly through our 'Work With Tesacola' commercial portal.",
    category: "BUSINESS",
    sortOrder: 4,
    isPublished: true,
  },
];

export const SEED_JOURNAL = [
  {
    id: "jn-1",
    title: "The Anatomy of a Wholecut: Why One Piece of Leather Commands Reverence",
    slug: "anatomy-of-a-wholecut",
    excerpt: "Most dress shoes are assembled from six to nine distinct pattern pieces. The wholecut demands a single, uninterrupted skin with zero flaws.",
    content: "When crafting a wholecut oxford, there is nowhere to hide imperfections. A hide with even a minor blemish or scratch cannot be utilized. Our master clickers inspect hundreds of square feet of prime vegetable-tanned leather to find the rare section possessing the tensile uniformity and flawless pore structure required to endure the severe strain of three-dimensional lasting. Tesacola is building its own standard of Nigerian manufacturing.",
    author: "Tesacola Master Craftsman",
    coverImage: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=80",
    tags: ["Craft", "Leather", "Heritage"],
    isPublished: true,
    publishedAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "jn-2",
    title: "Enjoying Trust & Quality: The Philosophy Behind Nigerian Industrial Craft",
    slug: "enjoying-trust-and-quality",
    excerpt: "Beyond luxury aesthetics lies the foundation of commercial trust: dependable construction, durable materials, and transparent lead times.",
    content: "Our brand sign-off—'Enjoying Trust & Quality'—is not a slogan; it is our operational framework. From sourcing heavy hides to verifying tensile stitch ratings and guaranteeing dimensional stability, Tesacola stands as a testament to Nigerian manufacturing capable of commanding respect across international capitals.",
    author: "Editorial Team",
    coverImage: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=80",
    tags: ["Philosophy", "Manufacturing", "Nigeria"],
    isPublished: true,
    publishedAt: "2026-09-01T12:00:00Z",
  },
];
